services:
  db:
    build:
      context: .
      dockerfile: db.dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      HOST: ${HOST}
      PORT: 8080
      ENVIRONMENT: ${ENVIRONMENT}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_DOMAIN_NAME: ${BACKEND_DOMAIN_NAME}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      SESSION_KEY: ${SESSION_KEY}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      TWITCH_WEBHOOK_URL: ${TWITCH_WEBHOOK_URL}
      TWITCH_WEBHOOK_SECRET: ${TWITCH_WEBHOOK_SECRET}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
    depends_on:
      - db
      - migrate
    healthcheck:
      test: ["CMD", "curl", "-f", "${HOST}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  migrate:
    build:
      context: .
      dockerfile: migrate.dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "echo", "Migration complete"]
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 5s

volumes:
  db_data:

