// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Redemption struct {
	MessageID  string             `json:"message_id"`
	StreamerID pgtype.Text        `json:"streamer_id"`
	ViewerID   pgtype.Text        `json:"viewer_id"`
	RedeemedAt pgtype.Timestamptz `json:"redeemed_at"`
}

type Reward struct {
	RewardID   string             `json:"reward_id"`
	StreamerID pgtype.Text        `json:"streamer_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Streamer struct {
	TwitchID        string             `json:"twitch_id"`
	Username        string             `json:"username"`
	Verified        pgtype.Bool        `json:"verified"`
	ProfileImageUrl pgtype.Text        `json:"profile_image_url"`
	AccessToken     pgtype.Text        `json:"access_token"`
	RefreshToken    pgtype.Text        `json:"refresh_token"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	IsLive          pgtype.Bool        `json:"is_live"`
}

type Viewer struct {
	TwitchID     string             `json:"twitch_id"`
	Username     string             `json:"username"`
	RegisteredIn pgtype.Text        `json:"registered_in"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
